
Vue.component('dummy-text', {
  props: ['scrub'],
  template: `
<div>
<p>{{scrub}}</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc leo turpis, vestibulum a purus sed, imperdiet ultricies lorem. Vivamus maximus tortor lectus, vitae suscipit lorem sodales id. Sed maximus consequat tortor at dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam efficitur magna in sapien lobortis finibus laoreet nec urna. Pellentesque non sollicitudin tellus. Nullam suscipit lorem felis, eu condimentum odio posuere at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum semper velit eget ornare elementum. Etiam nec eros vitae urna mattis consequat sit amet vitae eros. Nunc ut quam sem. Suspendisse ut lacinia libero. Ut interdum sollicitudin mi sit amet fringilla. Phasellus sed felis id ex egestas consequat.</p>

<p>Fusce cursus lacus et metus egestas, eu euismod metus aliquam. Quisque velit ligula, semper ac dui at, tincidunt tristique est. Nunc efficitur pulvinar ante, a ultrices massa vulputate id. Integer ultrices malesuada velit at tempus. Quisque blandit volutpat nisl eget porta. Ut a mauris nunc. Donec convallis sapien elit, quis auctor sem commodo id. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dapibus, enim ut molestie viverra, velit diam tincidunt lectus, quis varius tortor dui at diam. Pellentesque quis feugiat urna. Sed efficitur nunc risus, sed sagittis lacus finibus vel. Quisque sodales velit enim, eu cursus neque feugiat a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst.</p>

<p>Aenean tortor lacus, scelerisque in tincidunt malesuada, cursus ut arcu. Ut felis quam, luctus sed ornare a, sagittis in lectus. Duis eget lorem quis risus vehicula gravida vel vitae quam. Curabitur elementum, tortor vitae tristique sollicitudin, sem nibh sodales diam, convallis interdum dui eros sed nisl. Vestibulum vitae est non elit tempor tincidunt fermentum nec lectus. Sed dictum congue felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam feugiat tortor scelerisque dui hendrerit facilisis. Ut quam lorem, ultrices a augue ac, hendrerit laoreet ipsum. Duis quis diam magna. In varius dignissim iaculis. Nunc ullamcorper, elit a consectetur euismod, augue ipsum pellentesque turpis, eu commodo ex lectus eu massa. Integer et pulvinar nunc. Morbi commodo semper ex et molestie. Fusce tincidunt sollicitudin arcu, sit amet lobortis odio. Proin facilisis nibh quis convallis scelerisque.</p>

<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc eget odio interdum, tempus libero eget, efficitur tellus. Vivamus mattis risus in sapien lacinia, eleifend lacinia elit varius. Nam pulvinar nisl eu augue porta, nec placerat neque gravida. Donec tempus feugiat ipsum at viverra. Fusce mollis mi quis sapien pulvinar, sit amet fringilla est scelerisque. Sed imperdiet dolor non vulputate semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mattis massa at orci auctor, eget malesuada nisi facilisis. Maecenas condimentum fringilla condimentum.</p>

<p>Pellentesque in leo ut augue porttitor congue. Phasellus dolor orci, facilisis at tellus at, blandit laoreet mi. Phasellus ut gravida sem, nec dignissim tellus. Nam in felis rutrum, porta nibh interdum, commodo purus. Morbi id neque quis nulla fringilla porttitor non a nulla. Praesent placerat scelerisque augue sed tempus. Quisque vitae mollis nibh. Donec finibus mollis dui, eget iaculis est porttitor sed.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc leo turpis, vestibulum a purus sed, imperdiet ultricies lorem. Vivamus maximus tortor lectus, vitae suscipit lorem sodales id. Sed maximus consequat tortor at dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam efficitur magna in sapien lobortis finibus laoreet nec urna. Pellentesque non sollicitudin tellus. Nullam suscipit lorem felis, eu condimentum odio posuere at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum semper velit eget ornare elementum. Etiam nec eros vitae urna mattis consequat sit amet vitae eros. Nunc ut quam sem. Suspendisse ut lacinia libero. Ut interdum sollicitudin mi sit amet fringilla. Phasellus sed felis id ex egestas consequat.</p>

<p>Fusce cursus lacus et metus egestas, eu euismod metus aliquam. Quisque velit ligula, semper ac dui at, tincidunt tristique est. Nunc efficitur pulvinar ante, a ultrices massa vulputate id. Integer ultrices malesuada velit at tempus. Quisque blandit volutpat nisl eget porta. Ut a mauris nunc. Donec convallis sapien elit, quis auctor sem commodo id. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dapibus, enim ut molestie viverra, velit diam tincidunt lectus, quis varius tortor dui at diam. Pellentesque quis feugiat urna. Sed efficitur nunc risus, sed sagittis lacus finibus vel. Quisque sodales velit enim, eu cursus neque feugiat a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst.</p>

<p>Aenean tortor lacus, scelerisque in tincidunt malesuada, cursus ut arcu. Ut felis quam, luctus sed ornare a, sagittis in lectus. Duis eget lorem quis risus vehicula gravida vel vitae quam. Curabitur elementum, tortor vitae tristique sollicitudin, sem nibh sodales diam, convallis interdum dui eros sed nisl. Vestibulum vitae est non elit tempor tincidunt fermentum nec lectus. Sed dictum congue felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam feugiat tortor scelerisque dui hendrerit facilisis. Ut quam lorem, ultrices a augue ac, hendrerit laoreet ipsum. Duis quis diam magna. In varius dignissim iaculis. Nunc ullamcorper, elit a consectetur euismod, augue ipsum pellentesque turpis, eu commodo ex lectus eu massa. Integer et pulvinar nunc. Morbi commodo semper ex et molestie. Fusce tincidunt sollicitudin arcu, sit amet lobortis odio. Proin facilisis nibh quis convallis scelerisque.</p>

<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc eget odio interdum, tempus libero eget, efficitur tellus. Vivamus mattis risus in sapien lacinia, eleifend lacinia elit varius. Nam pulvinar nisl eu augue porta, nec placerat neque gravida. Donec tempus feugiat ipsum at viverra. Fusce mollis mi quis sapien pulvinar, sit amet fringilla est scelerisque. Sed imperdiet dolor non vulputate semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mattis massa at orci auctor, eget malesuada nisi facilisis. Maecenas condimentum fringilla condimentum.</p>

<p>Pellentesque in leo ut augue porttitor congue. Phasellus dolor orci, facilisis at tellus at, blandit laoreet mi. Phasellus ut gravida sem, nec dignissim tellus. Nam in felis rutrum, porta nibh interdum, commodo purus. Morbi id neque quis nulla fringilla porttitor non a nulla. Praesent placerat scelerisque augue sed tempus. Quisque vitae mollis nibh. Donec finibus mollis dui, eget iaculis est porttitor sed.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc leo turpis, vestibulum a purus sed, imperdiet ultricies lorem. Vivamus maximus tortor lectus, vitae suscipit lorem sodales id. Sed maximus consequat tortor at dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam efficitur magna in sapien lobortis finibus laoreet nec urna. Pellentesque non sollicitudin tellus. Nullam suscipit lorem felis, eu condimentum odio posuere at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum semper velit eget ornare elementum. Etiam nec eros vitae urna mattis consequat sit amet vitae eros. Nunc ut quam sem. Suspendisse ut lacinia libero. Ut interdum sollicitudin mi sit amet fringilla. Phasellus sed felis id ex egestas consequat.</p>

<p>Fusce cursus lacus et metus egestas, eu euismod metus aliquam. Quisque velit ligula, semper ac dui at, tincidunt tristique est. Nunc efficitur pulvinar ante, a ultrices massa vulputate id. Integer ultrices malesuada velit at tempus. Quisque blandit volutpat nisl eget porta. Ut a mauris nunc. Donec convallis sapien elit, quis auctor sem commodo id. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dapibus, enim ut molestie viverra, velit diam tincidunt lectus, quis varius tortor dui at diam. Pellentesque quis feugiat urna. Sed efficitur nunc risus, sed sagittis lacus finibus vel. Quisque sodales velit enim, eu cursus neque feugiat a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst.</p>

<p>Aenean tortor lacus, scelerisque in tincidunt malesuada, cursus ut arcu. Ut felis quam, luctus sed ornare a, sagittis in lectus. Duis eget lorem quis risus vehicula gravida vel vitae quam. Curabitur elementum, tortor vitae tristique sollicitudin, sem nibh sodales diam, convallis interdum dui eros sed nisl. Vestibulum vitae est non elit tempor tincidunt fermentum nec lectus. Sed dictum congue felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam feugiat tortor scelerisque dui hendrerit facilisis. Ut quam lorem, ultrices a augue ac, hendrerit laoreet ipsum. Duis quis diam magna. In varius dignissim iaculis. Nunc ullamcorper, elit a consectetur euismod, augue ipsum pellentesque turpis, eu commodo ex lectus eu massa. Integer et pulvinar nunc. Morbi commodo semper ex et molestie. Fusce tincidunt sollicitudin arcu, sit amet lobortis odio. Proin facilisis nibh quis convallis scelerisque.</p>

<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc eget odio interdum, tempus libero eget, efficitur tellus. Vivamus mattis risus in sapien lacinia, eleifend lacinia elit varius. Nam pulvinar nisl eu augue porta, nec placerat neque gravida. Donec tempus feugiat ipsum at viverra. Fusce mollis mi quis sapien pulvinar, sit amet fringilla est scelerisque. Sed imperdiet dolor non vulputate semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mattis massa at orci auctor, eget malesuada nisi facilisis. Maecenas condimentum fringilla condimentum.</p>

<p>Pellentesque in leo ut augue porttitor congue. Phasellus dolor orci, facilisis at tellus at, blandit laoreet mi. Phasellus ut gravida sem, nec dignissim tellus. Nam in felis rutrum, porta nibh interdum, commodo purus. Morbi id neque quis nulla fringilla porttitor non a nulla. Praesent placerat scelerisque augue sed tempus. Quisque vitae mollis nibh. Donec finibus mollis dui, eget iaculis est porttitor sed.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc leo turpis, vestibulum a purus sed, imperdiet ultricies lorem. Vivamus maximus tortor lectus, vitae suscipit lorem sodales id. Sed maximus consequat tortor at dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam efficitur magna in sapien lobortis finibus laoreet nec urna. Pellentesque non sollicitudin tellus. Nullam suscipit lorem felis, eu condimentum odio posuere at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum semper velit eget ornare elementum. Etiam nec eros vitae urna mattis consequat sit amet vitae eros. Nunc ut quam sem. Suspendisse ut lacinia libero. Ut interdum sollicitudin mi sit amet fringilla. Phasellus sed felis id ex egestas consequat.</p>

<p>Fusce cursus lacus et metus egestas, eu euismod metus aliquam. Quisque velit ligula, semper ac dui at, tincidunt tristique est. Nunc efficitur pulvinar ante, a ultrices massa vulputate id. Integer ultrices malesuada velit at tempus. Quisque blandit volutpat nisl eget porta. Ut a mauris nunc. Donec convallis sapien elit, quis auctor sem commodo id. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dapibus, enim ut molestie viverra, velit diam tincidunt lectus, quis varius tortor dui at diam. Pellentesque quis feugiat urna. Sed efficitur nunc risus, sed sagittis lacus finibus vel. Quisque sodales velit enim, eu cursus neque feugiat a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst.</p>

<p>Aenean tortor lacus, scelerisque in tincidunt malesuada, cursus ut arcu. Ut felis quam, luctus sed ornare a, sagittis in lectus. Duis eget lorem quis risus vehicula gravida vel vitae quam. Curabitur elementum, tortor vitae tristique sollicitudin, sem nibh sodales diam, convallis interdum dui eros sed nisl. Vestibulum vitae est non elit tempor tincidunt fermentum nec lectus. Sed dictum congue felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam feugiat tortor scelerisque dui hendrerit facilisis. Ut quam lorem, ultrices a augue ac, hendrerit laoreet ipsum. Duis quis diam magna. In varius dignissim iaculis. Nunc ullamcorper, elit a consectetur euismod, augue ipsum pellentesque turpis, eu commodo ex lectus eu massa. Integer et pulvinar nunc. Morbi commodo semper ex et molestie. Fusce tincidunt sollicitudin arcu, sit amet lobortis odio. Proin facilisis nibh quis convallis scelerisque.</p>

<p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc eget odio interdum, tempus libero eget, efficitur tellus. Vivamus mattis risus in sapien lacinia, eleifend lacinia elit varius. Nam pulvinar nisl eu augue porta, nec placerat neque gravida. Donec tempus feugiat ipsum at viverra. Fusce mollis mi quis sapien pulvinar, sit amet fringilla est scelerisque. Sed imperdiet dolor non vulputate semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur mattis massa at orci auctor, eget malesuada nisi facilisis. Maecenas condimentum fringilla condimentum.</p>

<p>Pellentesque in leo ut augue porttitor congue. Phasellus dolor orci, facilisis at tellus at, blandit laoreet mi. Phasellus ut gravida sem, nec dignissim tellus. Nam in felis rutrum, porta nibh interdum, commodo purus. Morbi id neque quis nulla fringilla porttitor non a nulla. Praesent placerat scelerisque augue sed tempus. Quisque vitae mollis nibh. Donec finibus mollis dui, eget iaculis est porttitor sed.</p>
</div>  
  `
});
